version: '3.8'
services:

  gitlab:
    image: gitlab/gitlab-ce:$GITLAB_VERSION
    restart: always
    container_name: gitlab
    hostname: $GITLAB_HOST
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://$GITLAB_HOST'
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/fullchain.pem'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/privkey.pem'
        nginx['ssl_dhparam'] = '/etc/gitlab/ssl/dhparams.pem'
        # Registry
        registry_external_url 'https://$GITLAB_HOST:5050'
        registry_nginx['ssl_certificate'] = '/etc/gitlab/ssl/fullchain.pem'
        registry_nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/privkey.pem'
        # Email Notifications GOOGLE TEMPLATE
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '$SMTP_ADDRESS'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = '$SMTP_USER_NAME'
        gitlab_rails['smtp_password'] = '$SMTP_PASSWORD'
        gitlab_rails['smtp_domain'] = '$SMTP_DOMAIN'
        gitlab_rails['gitlab_email_from'] = '$GITLAB_EMAIL_FROM'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['smtp_tls'] = false
    expose:
      - '5050'
    ports:
      - '8080:8080'
      - '443:443'
      - '22:22'
      - '587:587'
      - '5050:5050'
    volumes:
      - $GITLAB_HOME/config:/etc/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/config/ssl:/etc/gitlab/ssl

  gitlab_runner:
    image: gitlab/gitlab-runner:$GITLAB_RUNNER_VERSION
    restart: always
    container_name: gitlab_runner
    environment:
      - CI_SERVER_URL=https://$GITLAB_HOST
    volumes:
      - $GITLAB_RUNNER_HOME:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw
